import { NextResponse, type NextRequest } from "next/server";
import { getScan } from "@/lib/scanner/store";

export const GET = (_req: NextRequest, { params }: { params: Promise<{ id: string }> }) => {
  return params.then(({ id }) => {
    const scan = getScan(id);
    if (!scan) {
      return NextResponse.json({ error: "Scan not found" }, { status: 404 });
    }

    const hostname = new URL(scan.target).hostname;
    const s = scan.summary;

    const severityEmoji = (sev: string) => {
      switch (sev) {
        case "critical": return "🔴";
        case "high": return "🟠";
        case "medium": return "🟡";
        case "low": return "🔵";
        default: return "⚪";
      }
    };

    const lines: string[] = [
      `# VibeShield Security Report`,
      `## ${hostname}`,
      ``,
      `| Field | Value |`,
      `|-------|-------|`,
      `| **Target** | ${scan.target} |`,
      `| **Grade** | ${scan.grade} (${scan.score}/100) |`,
      `| **Status** | ${scan.status} |`,
      `| **Scanned** | ${new Date(scan.startedAt).toUTCString()} |`,
      scan.completedAt ? `| **Duration** | ${Math.round((new Date(scan.completedAt).getTime() - new Date(scan.startedAt).getTime()) / 1000)}s |` : "",
      `| **Technologies** | ${scan.technologies.join(", ") || "None detected"} |`,
      scan.isSpa ? `| **SPA** | Yes |` : "",
      scan.surface ? `| **Pages crawled** | ${scan.surface.pages} |` : "",
      scan.surface ? `| **API endpoints** | ${scan.surface.apiEndpoints} |` : "",
      scan.surface ? `| **JS bundles** | ${scan.surface.jsFiles} |` : "",
      ``,
      `### Summary`,
      ``,
      `| Critical | High | Medium | Low | Info | Total |`,
      `|----------|------|--------|-----|------|-------|`,
      `| ${s.critical} | ${s.high} | ${s.medium} | ${s.low} | ${s.info} | ${s.total} |`,
      ``,
    ];

    // Comparison section (if rescan)
    if (scan.comparison) {
      const c = scan.comparison;
      const scoreDir = c.delta.score > 0 ? "improved" : c.delta.score < 0 ? "regressed" : "unchanged";
      lines.push(
        `### Comparison with Previous Scan`, ``,
        `| Metric | Previous | Current | Delta |`,
        `|--------|----------|---------|-------|`,
        `| Grade | ${c.previousGrade} | ${scan.grade} | ${c.delta.score > 0 ? "+" : ""}${c.delta.score} |`,
        `| Score | ${c.previousScore} | ${scan.score} | ${scoreDir} |`,
        `| Findings | ${c.previousFindings} | ${s.total} | ${c.delta.findings > 0 ? "+" : ""}${c.delta.findings} |`,
        ``,
      );
      if (c.fixedFindings && c.fixedFindings.length > 0) {
        lines.push(`**Fixed:** ${c.fixedFindings.map((f) => f.title).join(", ")}`, ``);
      }
      if (c.newFindings && c.newFindings.length > 0) {
        lines.push(`**New:** ${c.newFindings.map((f) => f.title).join(", ")}`, ``);
      }
    }

    // Module results
    if (scan.modules.length > 0) {
      const completed = scan.modules.filter((m) => m.status === "completed");
      const passed = completed.filter((m) => m.findingsCount === 0);
      const failed = scan.modules.filter((m) => m.status === "failed");
      lines.push(
        `### Module Results`, ``,
        `${completed.length} modules completed, ${passed.length} passed, ${completed.length - passed.length} found issues${failed.length > 0 ? `, ${failed.length} failed` : ""}`,
        ``,
      );
    }

    if (scan.findings.length > 0) {
      lines.push(`### Findings`, ``);

      const grouped = new Map<string, typeof scan.findings>();
      for (const f of scan.findings) {
        const key = f.module;
        if (!grouped.has(key)) grouped.set(key, []);
        grouped.get(key)!.push(f);
      }

      for (const [module, findings] of grouped) {
        lines.push(`#### ${module}`, ``);
        for (const f of findings) {
          lines.push(
            `${severityEmoji(f.severity)} **${f.severity.toUpperCase()}** — ${f.title}`,
            ``,
            `> ${f.description}`,
            ``,
          );
          if (f.evidence) {
            lines.push(`<details><summary>Evidence</summary>`, ``, "```", f.evidence, "```", ``, `</details>`, ``);
          }
          lines.push(`**Remediation:** ${f.remediation}`, ``);
          if (f.codeSnippet) {
            lines.push(`<details><summary>Code Fix</summary>`, ``, "```ts", f.codeSnippet, "```", ``, `</details>`, ``);
          }
          if (f.cwe || f.owasp) {
            const refs = [f.cwe, f.owasp ? `OWASP ${f.owasp}` : ""].filter(Boolean).join(" | ");
            lines.push(`*${refs}*`, ``);
          }
          lines.push(`---`, ``);
        }
      }
    } else {
      lines.push(`### No vulnerabilities found ✅`, ``, `Your app passed all security checks.`, ``);
    }

    lines.push(``, `---`, `*Generated by [VibeShield](https://vibeshield.dev) — Black-box pentesting for vibe-coded apps*`);

    const markdown = lines.filter((l) => l !== undefined).join("\n");

    return new NextResponse(markdown, {
      headers: {
        "Content-Type": "text/markdown; charset=utf-8",
        "Content-Disposition": `attachment; filename="vibeshield-${hostname}-report.md"`,
      },
    });
  });
};
